apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: distributor
    app.kubernetes.io/managed-by: kustomize
  name: distributor-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: distributor
  name: distributor-worker
  namespace: distributor-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: distributor
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: distributor
    spec:
      containers:
      - args:
        - --redis-password='123456' 
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: controller
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: webserver:latest
        imagePullPolicy: IfNotPresent
        name: web
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: distributor
      serviceAccountName: distributor
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /data
          type: ""
        name: data
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
