# permissions for end users to edit distributions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: distributor
    app.kubernetes.io/managed-by: kustomize
  name: distribution-editor-role
rules:
- apiGroups:
  - distributor.distributor.io
  resources:
  - distributions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distributor.distributor.io
  resources:
  - distributions/status
  verbs:
  - get
